### ISSUE TITLE
git fsck warning

### ISSUE THREAD

**Issue by cjcjameson** [tsaleh/tammersaleh.com#82]
Hi there,

I was cloning my fork of this, and I needed to `git clone --config transfer.fsckobjects=false git@github.com:cjcjameson/tammersaleh.com.git` in order to let the clone go through.

`git fsck` shows the warning:
`warning in tree 48ee09bf6cda7c97042297d09dfcafefd6f53c96: zeroPaddedFilemode: contains zero-padded file modes`

I'll leave it to you if you wanted to resolve that -- seems like it'd be rather invasive, however.

**Comment by tsaleh** [comment]
Yeah, googling, it seems like the issue is innocuous, and the fix very invasive (force-push with all new SHAs).  Might do so later, when there aren't any open branches.   Closing this for now.
